server:
  port: 7001
spring:
  application:
    name: serverA
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CST
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver